/*
 * This file is automatically generated.  Do not edit.
 */
#define VERSION "0.5"
#define GIT_BRANCH "master"
#define GIT_HASH "cf0fcb0575096a2b40e0fb33707cf4da91a72eee"
#define GIT_HASH_SHORT "cf0fcb0"
#define GIT_DATE "2022-06-28 05:26:20 +0000"
